logging:
  level:
    org:
      hibernate:
        SQL: debug

security:
  matchers:
    anonymous: /login, /user/add
    public: /
    user: /user/**
    admin: /admin/**
    login: /login
    
jwt:
  sing:
    key: my-key
  time-to-live: 120000